### ISSUE TITLE
Click-Out from Strategy-Tab saves the strategy.

### ISSUE THREAD

**Issue by rsheep** [codebroken/BrokenBot#14]
How to reproduce:
Download latest sources and compile BrokenBot with Aut2Exe.
Run BrokenBot.
Now you can click between General and Strategy tab. You will notice that every time you are on the Strategy tab and you click to display the General tab the "Standard - default" strategy is saved again&again.

**Comment by codebroken** [comment]
This is by design.  The form is actually destroyed in the background so if you didn't manually save then any edits you made are now gone.
