### ISSUE TITLE
Not drop all giants in one wave - it's no good i think

### ISSUE THREAD

**Issue by Plushkin** [codebroken/BrokenBot#9]
![image](https://cloud.githubusercontent.com/assets/12173683/7503748/97a5d15a-f44d-11e4-9582-bd2794d40406.png)
![image](https://cloud.githubusercontent.com/assets/12173683/7503769/bfc61d48-f44d-11e4-9141-41f0d719a216.png)

**Comment by Plushkin** [comment]
work better only all tropps

**Comment by Plushkin** [comment]
How to drope giants in line like barbarian or archer?

**Comment by maxcom99** [comment]
This is a suggestion. Visit the site.
